services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - temporal-network
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
networks:
  temporal-network:
    external: true