FROM node:23.10.0

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
